<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Gomar">
<meta name="dcterms.date" content="2024-05-16">

<title>Daniel Gomar - Multinomial Logit Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Daniel Gomar</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estimating-yogurt-preferences" id="toc-estimating-yogurt-preferences" class="nav-link active" data-scroll-target="#estimating-yogurt-preferences">1. Estimating Yogurt Preferences</a>
  <ul class="collapse">
  <li><a href="#likelihood-for-the-multi-nomial-logit-mnl-model" id="toc-likelihood-for-the-multi-nomial-logit-mnl-model" class="nav-link" data-scroll-target="#likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</a></li>
  <li><a href="#yogurt-dataset" id="toc-yogurt-dataset" class="nav-link" data-scroll-target="#yogurt-dataset">Yogurt Dataset</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#dollar-benefit-calculation" id="toc-dollar-benefit-calculation" class="nav-link" data-scroll-target="#dollar-benefit-calculation">Dollar Benefit Calculation</a></li>
  </ul></li>
  <li><a href="#estimating-minivan-preferences" id="toc-estimating-minivan-preferences" class="nav-link" data-scroll-target="#estimating-minivan-preferences">2. Estimating Minivan Preferences</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#predicted-market-shares-for-minivans" id="toc-predicted-market-shares-for-minivans" class="nav-link" data-scroll-target="#predicted-market-shares-for-minivans">Predicted Market Shares for Minivans</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multinomial Logit Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Gomar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This assignment uses uses the MNL model to analyze (1) yogurt purchase data made by consumers at a retail location, and (2) conjoint data about consumer preferences for minivans.</p>
<section id="estimating-yogurt-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-yogurt-preferences">1. Estimating Yogurt Preferences</h2>
<section id="likelihood-for-the-multi-nomial-logit-mnl-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</h3>
<p>Suppose we have <span class="math inline">\(i=1,\ldots,n\)</span> consumers who each select exactly one product <span class="math inline">\(j\)</span> from a set of <span class="math inline">\(J\)</span> products. The outcome variable is the identity of the product chosen <span class="math inline">\(y_i \in \{1, \ldots, J\}\)</span> or equivalently a vector of <span class="math inline">\(J-1\)</span> zeros and <span class="math inline">\(1\)</span> one, where the <span class="math inline">\(1\)</span> indicates the selected product. For example, if the third product was chosen out of 4 products, then either <span class="math inline">\(y=3\)</span> or <span class="math inline">\(y=(0,0,1,0)\)</span> depending on how we want to represent it. Suppose also that we have a vector of data on each product <span class="math inline">\(x_j\)</span> (eg, size, price, etc.).</p>
<p>We model the consumer’s decision as the selection of the product that provides the most utility, and we’ll specify the utility function as a linear function of the product characteristics:</p>
<p><span class="math display">\[ U_{ij} = x_j'\beta + \epsilon_{ij} \]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an i.i.d. extreme value error term.</p>
<p>The choice of the i.i.d. extreme value error term leads to a closed-form expression for the probability that consumer <span class="math inline">\(i\)</span> chooses product <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[ \mathbb{P}_i(j) = \frac{e^{x_j'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>For example, if there are 4 products, the probability that consumer <span class="math inline">\(i\)</span> chooses product 3 is:</p>
<p><span class="math display">\[ \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{e^{x_1'\beta} + e^{x_2'\beta} + e^{x_3'\beta} + e^{x_4'\beta}} \]</span></p>
<p>A clever way to write the individual likelihood function for consumer <span class="math inline">\(i\)</span> is the product of the <span class="math inline">\(J\)</span> probabilities, each raised to the power of an indicator variable (<span class="math inline">\(\delta_{ij}\)</span>) that indicates the chosen product:</p>
<p><span class="math display">\[ L_i(\beta) = \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} = \mathbb{P}_i(1)^{\delta_{i1}} \times \ldots \times \mathbb{P}_i(J)^{\delta_{iJ}}\]</span></p>
<p>Notice that if the consumer selected product <span class="math inline">\(j=3\)</span>, then <span class="math inline">\(\delta_{i3}=1\)</span> while <span class="math inline">\(\delta_{i1}=\delta_{i2}=\delta_{i4}=0\)</span> and the likelihood is:</p>
<p><span class="math display">\[ L_i(\beta) = \mathbb{P}_i(1)^0 \times \mathbb{P}_i(2)^0 \times \mathbb{P}_i(3)^1 \times \mathbb{P}_i(4)^0 = \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>The joint likelihood (across all consumers) is the product of the <span class="math inline">\(n\)</span> individual likelihoods:</p>
<p><span class="math display">\[ L_n(\beta) = \prod_{i=1}^n L_i(\beta) = \prod_{i=1}^n \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} \]</span></p>
<p>And the joint log-likelihood function is:</p>
<p><span class="math display">\[ \ell_n(\beta) = \sum_{i=1}^n \sum_{j=1}^J \delta_{ij} \log(\mathbb{P}_i(j)) \]</span></p>
</section>
<section id="yogurt-dataset" class="level3">
<h3 class="anchored" data-anchor-id="yogurt-dataset">Yogurt Dataset</h3>
<p>We will use the <code>yogurt_data</code> dataset, which provides anonymized consumer identifiers (<code>id</code>), a vector indicating the chosen product (<code>y1</code>:<code>y4</code>), a vector indicating if any products were “featured” in the store as a form of advertising (<code>f1</code>:<code>f4</code>), and the products’ prices (<code>p1</code>:<code>p4</code>). For example, consumer 1 purchased yogurt 4 at a price of 0.079/oz and none of the yogurts were featured/advertised at the time of consumer 1’s purchase. Consumers 2 through 7 each bought yogurt 2, etc.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
     id    y1    y2    y3    y4    f1    f2    f3    f4    p1     p2     p3
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1     1     0     0     0     1     0     0     0     0 0.108 0.081  0.0610
2     2     0     1     0     0     0     0     0     0 0.108 0.0980 0.0640
3     3     0     1     0     0     0     0     0     0 0.108 0.0980 0.0610
4     4     0     1     0     0     0     0     0     0 0.108 0.0980 0.0610
5     5     0     1     0     0     0     0     0     0 0.125 0.0980 0.0490
6     6     0     1     0     0     0     0     0     0 0.108 0.092  0.0500
# ℹ 1 more variable: p4 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Description of the yogurt data</p>
<p>This dataset contains the following variables:</p>
<p>-id: anonymized consumer identifiers -y: indicator variables showing which yogurt was purchased -f: indicator variables showing if a yogurt was featured in the store -p: continous variables indicating the prices of the yogurts</p>
<p>Each row in the dataset represents a unique purchase made by a consumer, and each set of columns (y1 to y4, f1 to f4, p1 to p4) pertains to the characteristics of the four yogurt products.</p>
<p>Let the vector of product features include brand dummy variables for yogurts 1-3 (we’ll omit a dummy for product 4 to avoid multi-collinearity), a dummy variable to indicate if a yogurt was featured, and a continuous variable for the yogurts’ prices:</p>
<p><span class="math display">\[ x_j' = [\mathbbm{1}(\text{Yogurt 1}), \mathbbm{1}(\text{Yogurt 2}), \mathbbm{1}(\text{Yogurt 3}), X_f, X_p] \]</span></p>
<p>The “hard part” of the MNL likelihood function is organizing the data, as we need to keep track of 3 dimensions (consumer <span class="math inline">\(i\)</span>, covariate <span class="math inline">\(k\)</span>, and product <span class="math inline">\(j\)</span>) instead of the typical 2 dimensions for cross-sectional regression models (consumer <span class="math inline">\(i\)</span> and covariate <span class="math inline">\(k\)</span>).</p>
<p>What we would like to do is reorganize the data from a “wide” shape with <span class="math inline">\(n\)</span> rows and multiple columns for each covariate, to a “long” shape with <span class="math inline">\(n \times J\)</span> rows and a single column for each covariate. As part of this re-organization, we’ll add binary variables to indicate the first 3 products; the variables for featured and price are included in the dataset and simply need to be “pivoted” or “melted” from wide to long.</p>
</section>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept Yogurt 1</td>
<td style="text-align: right;">1.4119707</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intercept Yogurt 2</td>
<td style="text-align: right;">0.6523545</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intercept Yogurt 3</td>
<td style="text-align: right;">-3.0846259</td>
</tr>
<tr class="even">
<td style="text-align: left;">Featured</td>
<td style="text-align: right;">0.3268772</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Price</td>
<td style="text-align: right;">-37.5763842</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>The estimated parameters for the intercepts of the three yogurts provide insight into consumer preferences for each yogurt type. These intercepts represent the baseline utility that consumers derive from each yogurt product before considering the effects of features such as being featured in the store or the price. The intercept values indicate the relative preference for each yogurt product. Higher intercepts suggest a higher baseline utility, which corresponds to a stronger inherent preference by consumers for that product, assuming other factors (like being featured or price) are constant. Yogurt 1, with an intercept of 1.4119707, has the highest baseline utility among the three products. This indicates that, all else being equal, consumers have the strongest inherent preference for Yogurt 1.</p>
<p>Yogurt 2, with an intercept of 0.6523545, also has a positive baseline utility, but it is lower than that of Yogurt 1. This suggests that consumers have a moderate preference for Yogurt 2. While it is preferred over Yogurt 3, it does not enjoy as strong a preference as Yogurt 1. In contrast, Yogurt 3 has an intercept of -3.0846259, which is a negative value. This indicates a significantly lower baseline utility compared to Yogurt 1 and Yogurt 2. Consequently, Yogurt 3 is the least preferred product among the three.</p>
<p>In general, the intercepts suggest that, in the absence of other factors, consumers have a strong preference for Yogurt 1, a moderate preference for Yogurt 2, and a significantly lower preference for Yogurt 3. This ranking provides valuable information for retailers and manufacturers, indicating that efforts to promote Yogurt 1 may capitalize on its existing strong preference, while strategies to improve the attractiveness of Yogurt 3 could be explored to enhance its competitive position in the market.</p>
</section>
<section id="dollar-benefit-calculation" class="level3">
<h3 class="anchored" data-anchor-id="dollar-benefit-calculation">Dollar Benefit Calculation</h3>
<p>The dollar benefit between the most-preferred yogurt (Yogurt 1) and the least-preferred yogurt (Yogurt 3) can be calculated using the utility difference and the dollar-per-util conversion factor.</p>
<p>Given the utility difference:</p>
<p><span class="math display">\[
\Delta U = \text{Intercept Yogurt 1} - \text{Intercept Yogurt 3}
\]</span></p>
<p>and the dollar-per-util conversion factor:</p>
<p><span class="math display">\[
\text{Dollar-per-Util Conversion Factor} = \frac{1}{|\beta_{\text{price}}|}
\]</span></p>
<p>The dollar benefit is calculated as:</p>
<p><span class="math display">\[
\text{Dollar Benefit} = \Delta U \times \text{Dollar-per-Util Conversion Factor} = ( \text{Intercept Yogurt 1} - \text{Intercept Yogurt 3} ) \times \frac{1}{|\beta_{\text{price}}|}
\]</span></p>
<p>Substituting the values:</p>
<p><span class="math display">\[
\text{Dollar Benefit} = (1.4119707 - (-3.0846259)) \times \frac{1}{37.5763842} = 4.4965966 \times \frac{1}{37.5763842} \approx 0.11965
\]</span></p>
<p>The dollar benefit between the most-preferred yogurt (Yogurt 1) and the least-preferred yogurt (Yogurt 3) is approximately $0.12 per unit. This value represents the per-unit monetary measure of brand value, indicating how much more consumers value Yogurt 1 over Yogurt 3.</p>
<p>One benefit of the MNL model is that we can simulate counterfactuals (eg, what if the price of yogurt 1 was $0.10/oz instead of $0.08/oz).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Product</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Initial Market Share</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">New Market Share</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.6542172</td>
<td style="text-align: right;">0.0230716</td>
<td style="text-align: right;">-0.6311455</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.4710059</td>
<td style="text-align: right;">0.7175646</td>
<td style="text-align: right;">0.2465587</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.0288812</td>
<td style="text-align: right;">0.0438084</td>
<td style="text-align: right;">0.0149273</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.2463129</td>
<td style="text-align: right;">0.3728599</td>
<td style="text-align: right;">0.1265470</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</div>
<p>When the price of Yogurt 1 is increased by $0.10, its market share drops dramatically from 65.4% to 2.3%. This indicates a strong price sensitivity among consumers for Yogurt 1. The significant decrease of approximately 63.1% in market share suggests that consumers are highly responsive to price changes for this product, and many switch to other yogurt options when the price of Yogurt 1 increases. Additionally, the market shares for the other yogurts increase as a result of this price change. This redistribution of market shares indicates that when the price of Yogurt 1 rises, consumers shift their preferences to the other available yogurts, with the largest portion shifting to Yogurt 2 and a smaller but notable shift to Yogurt 4. Therefore, the results clearly show that increasing the price of Yogurt 1 by $0.10 leads to a substantial decrease in its market share, highlighting the high price elasticity of demand for this yogurt. Consumers readily switch to alternative products when faced with a price increase for Yogurt 1.</p>
</section>
</section>
<section id="estimating-minivan-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-minivan-preferences">2. Estimating Minivan Preferences</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>This is how the dataset looks like:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  resp.id ques alt carpool seat cargo  eng price choice
1       1    1   1     yes    6   2ft  gas    35      0
2       1    1   2     yes    8   3ft  hyb    30      0
3       1    1   3     yes    6   3ft  gas    30      1
4       1    2   1     yes    6   2ft  gas    30      0
5       1    2   2     yes    7   3ft  gas    35      1
6       1    2   3     yes    6   2ft elec    35      0</code></pre>
</div>
</div>
<p>Based on the information collected, we know that:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Number of respondents: 200 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of choice tasks per respondent: 0.075 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of alternatives per choice task: 3 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The attributes (levels) were number of seats (6,7,8), cargo space (2ft, 3ft), engine type (gas, hybrid, electric), and price (in thousands of dollars).</p>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<table class="table">
<colgroup>
<col style="width: 63%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>5.532174</td>
<td>0.224186</td>
</tr>
<tr class="even">
<td>C(seat, Treatment(reference=“6”))[T.7]</td>
<td>-0.524752</td>
<td>0.059634</td>
</tr>
<tr class="odd">
<td>C(seat, Treatment(reference=“6”))[T.8]</td>
<td>-0.293085</td>
<td>0.058510</td>
</tr>
<tr class="even">
<td>C(cargo, Treatment(reference=“2ft”))[T.3ft]</td>
<td>0.438538</td>
<td>0.048706</td>
</tr>
<tr class="odd">
<td>C(eng, Treatment(reference=“gas”))[T.elec]</td>
<td>-1.434680</td>
<td>0.061794</td>
</tr>
<tr class="even">
<td>C(eng, Treatment(reference=“gas”))[T.hyb]</td>
<td>-0.760489</td>
<td>0.056919</td>
</tr>
<tr class="odd">
<td>price</td>
<td>-0.159133</td>
<td>0.006212</td>
</tr>
</tbody>
</table>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>The intercept in the multinomial logistic regression model has a coefficient of 5.532174 with a standard error of 0.224186. This value represents the baseline log-odds of choosing a car with the reference features (6 seats, 2ft cargo space, and a gas engine) when the price is hypothetically zero. It serves as the starting point against which other features are compared.</p>
<p>For the number of seats, the model shows that cars with 7 or 8 seats are less preferred compared to those with 6 seats. Specifically, the coefficient for cars with 7 seats is -0.524752 with a standard error of 0.059634, indicating a significant decrease in preference. Similarly, the coefficient for cars with 8 seats is -0.293085 with a standard error of 0.058510. Although cars with 8 seats are also less preferred than those with 6 seats, they are slightly more favored than cars with 7 seats.Regarding cargo space, the model reveals that cars with 3ft of cargo space are more preferred than those with 2ft. The positive coefficient of 0.438538 (standard error of 0.048706) for 3ft cargo space indicates a higher likelihood of choosing cars with larger cargo space compared to the reference level.</p>
<p>The engine type significantly influences preferences as well. Cars with gas engines are the most preferred. The coefficient for electric engines is -1.434680 with a standard error of 0.061794, showing a strong negative impact on preference. This suggests that electric engines are much less favored compared to gas engines. Hybrid engines also have a negative coefficient of -0.760489 (standard error of 0.056919), indicating they are less preferred than gas engines, but more so than electric engines. The price coefficient is -0.159133 with a standard error of 0.006212. This negative coefficient signifies that as the price of a car increases, the likelihood of it being chosen decreases. This finding aligns with common expectations that higher prices generally reduce consumer demand.</p>
<p>In general, the data shows that the most preferred car features are 6 seats, 3ft cargo space, and a gas engine. Conversely, increasing the number of seats to 7 or 8 reduces preference, with 7 seats being the least favored. Additionally, cars with electric engines are the least preferred, followed by hybrid engines, with gas engines being the most preferred. Lower prices also significantly enhance the likelihood of a car being chosen. This analysis provides valuable insights into customer preferences, which can guide product design and marketing strategies to better align with consumer demand.</p>
<p>The dollar value of having 3ft of cargo space compared to 2ft of cargo space is approximately $2.76. This means that customers are willing to pay about $2.76 more for a car with 3ft of cargo space compared to one with 2ft of cargo space. This result comes from the fact that the coefficient for 3ft space is 0.438538 and the price coefficient is -0.159133. Then, we know that the dollar-per-util is 1/|0.159133|, which will be 6.285 approximately. Finally, we just need to multiply the coefficient for 3ft space times the dollar-per-util, that will give us 2.76.</p>
<table class="table">
<thead>
<tr class="header">
<th>Minivan</th>
<th>Seats</th>
<th>Cargo</th>
<th>Engine</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>30</td>
</tr>
<tr class="even">
<td>B</td>
<td>6</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="odd">
<td>C</td>
<td>8</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="even">
<td>D</td>
<td>7</td>
<td>3</td>
<td>Gas</td>
<td>40</td>
</tr>
<tr class="odd">
<td>E</td>
<td>6</td>
<td>2</td>
<td>Elec</td>
<td>40</td>
</tr>
<tr class="even">
<td>F</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>35</td>
</tr>
</tbody>
</table>
</section>
<section id="predicted-market-shares-for-minivans" class="level3">
<h3 class="anchored" data-anchor-id="predicted-market-shares-for-minivans">Predicted Market Shares for Minivans</h3>
<p>To predict the market shares of the six minivans, we used the following utility calculation equation:</p>
<p><span class="math display">\[
U_i = \text{Intercept} + \sum (\text{Feature Coefficient} \times \text{Feature Value}) + (\text{Price Coefficient} \times \text{Price})
\]</span></p>
<p>Using this equation, we calculated the utilities for each minivan and then applied the softmax function to determine the market shares. The results are summarized in the table below:</p>
<table class="table">
<thead>
<tr class="header">
<th>Minivan</th>
<th>Market Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>11.61%</td>
</tr>
<tr class="even">
<td>B</td>
<td>41.95%</td>
</tr>
<tr class="odd">
<td>C</td>
<td>31.30%</td>
</tr>
<tr class="even">
<td>D</td>
<td>7.84%</td>
</tr>
<tr class="odd">
<td>E</td>
<td>2.04%</td>
</tr>
<tr class="even">
<td>F</td>
<td>5.25%</td>
</tr>
</tbody>
</table>
<p>The utility values for each minivan were calculated as follows:</p>
<ul>
<li><p><strong>Minivan A (Seats: 7, Cargo: 2ft, Engine: Hybrid, Price: 30)</strong> <span class="math display">\[
U_A = 5.532174 + (-0.524752) + 0 + (-0.760489) + (-0.159133 \times 30) = -0.526056
\]</span></p></li>
<li><p><strong>Minivan B (Seats: 6, Cargo: 2ft, Engine: Gas, Price: 30)</strong> <span class="math display">\[
U_B = 5.532174 + 0 + 0 + 0 + (-0.159133 \times 30) = 0.758184
\]</span></p></li>
<li><p><strong>Minivan C (Seats: 8, Cargo: 2ft, Engine: Gas, Price: 30)</strong> <span class="math display">\[
U_C = 5.532174 + (-0.293085) + 0 + 0 + (-0.159133 \times 30) = 0.465099
\]</span></p></li>
<li><p><strong>Minivan D (Seats: 7, Cargo: 3ft, Engine: Gas, Price: 40)</strong> <span class="math display">\[
U_D = 5.532174 + (-0.524752) + 0.438538 + 0 + (-0.159133 \times 40) = -0.91936
\]</span></p></li>
<li><p><strong>Minivan E (Seats: 6, Cargo: 2ft, Engine: Elec, Price: 40)</strong> <span class="math display">\[
U_E = 5.532174 + 0 + 0 + (-1.434680) + (-0.159133 \times 40) = -2.267826
\]</span></p></li>
<li><p><strong>Minivan F (Seats: 7, Cargo: 2ft, Engine: Hybrid, Price: 35)</strong> <span class="math display">\[
U_F = 5.532174 + (-0.524752) + 0 + (-0.760489) + (-0.159133 \times 35) = -1.323222
\]</span></p></li>
</ul>
<p>After calculating these utility values, we transformed them using the softmax function to derive the market shares. The conclusion of the analysis shows that Minivan B is expected to capture the largest market share at 41.95%, followed by Minivan C with 31.30%. Minivans A, D, F, and E capture smaller shares, with Minivan E being the least preferred at 2.04%.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>