project:
  type: website
  output-dir: docs
  
website:
  title: "Daniel Gomar"
  navbar:
    left:
      - href: index.qmd
        text: About
 ##     - about.qmd
      #- href: resume.qmd
      #  text: Resume
      - href: projects.qmd
        text: Projects
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



